-- Демонстрационная предметная область интернет-магазина.

CREATE TABLE IF NOT EXISTS public.customers (
    id           bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email        varchar(256) NOT NULL UNIQUE,
    full_name    varchar(256) NOT NULL,
    created_at   timestamptz  NOT NULL DEFAULT now(),
    updated_at   timestamptz  NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.products (
    id           bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sku          varchar(64)  NOT NULL UNIQUE,
    title        varchar(512) NOT NULL,
    price_cents  integer      NOT NULL,
    in_stock     boolean      NOT NULL DEFAULT true,
    updated_at   timestamptz  NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.orders (
    id           bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customer_id  bigint       NOT NULL REFERENCES public.customers(id),
    status       varchar(32)  NOT NULL DEFAULT 'NEW',
    total_cents  integer      NOT NULL,
    created_at   timestamptz  NOT NULL DEFAULT now(),
    updated_at   timestamptz  NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.order_items (
    id           bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id     bigint       NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id   bigint       NOT NULL REFERENCES public.products(id),
    qty          integer      NOT NULL,
    price_cents  integer      NOT NULL,
    created_at   timestamptz  NOT NULL DEFAULT now()
);

-- Роль для CDC-подключения Debezium.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'dataflow_cdc') THEN
        CREATE ROLE dataflow_cdc WITH LOGIN REPLICATION PASSWORD 'dataflow_cdc';
    END IF;
END $$;

GRANT USAGE ON SCHEMA public TO dataflow_cdc;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO dataflow_cdc;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO dataflow_cdc;

-- Публикация с явным перечнем таблиц.
DROP PUBLICATION IF EXISTS shop_pub;
CREATE PUBLICATION shop_pub FOR TABLE
    public.customers,
    public.products,
    public.orders,
    public.order_items;

-- Минимальная начальная загрузка.
INSERT INTO public.products(sku, title, price_cents)
VALUES
    ('SKU-1001', 'Mug 350ml',     59900),
    ('SKU-1002', 'T-shirt M',    149900),
    ('SKU-1003', 'Notebook A5',   29900),
    ('SKU-1004', 'Pen 0.5mm',     19900)
ON CONFLICT (sku) DO NOTHING;

INSERT INTO public.customers(email, full_name)
VALUES
    ('alice@example.com', 'Alice Anderson'),
    ('bob@example.com',   'Bob Brown')
ON CONFLICT (email) DO NOTHING;
